### ISSUE TITLE
获取数据上有一些小问题

### ISSUE THREAD

**Issue by DRNTT** [myhhub/InStock#1]
作者您好，我这两天跑了一下您的项目，发现了一些小问题，对源码进行了一些修改。
关于数据获取日期的指定问题，我这里感觉有一些bug，不知道是不是我个人理解错误，希望您可以加我qq，我想详细咨询一下。
QQ号：444527845

**Comment by myhhub** [comment]
你是说收盘前获取前一个交易日的数据？
收盘前当日数据不完整，收盘后还要再获取一遍，没有必要搞多次，而且“大宗交易”数据收盘后1~2小时才会有。项目目前处于开发初期，更新频繁不建议自行修改代码。

**Comment by myhhub** [comment]
> 作者您好，我这两天跑了一下您的项目，发现了一些小问题，对源码进行了一些修改。 关于数据获取日期的指定问题，我这里感觉有一些bug，不知道是不是我个人理解错误，希望您可以加我qq，我想详细咨询一下。 QQ号：444527845

现在对这个问题进行了处理，应该是最优方案。
```
....
  if run_fun.__name__.startswith('save_nph'):
      run_fun(run_date, False)
....
```
```

def save_nph_stock_spot_data(date, before=True):
    if before and not runt.is_get_data(date):
        return
....
```
