### ISSUE TITLE
补全历史数据的时候，能否添加一个进度？

### ISSUE THREAD

**Issue by lhw828** [myhhub/InStock#11]
1、补全历史数据的时候，能否添加一个进度？
昨天执行了一个 `python InStock/instock/job/execute_daily_job.py 2022-01-01 2023-04-21`后，然后就是极度漫长的等待，挂在那一整夜，早上看，还是一动不动。看进程，看日志，都是一动不动的，不知道他到底有没有在运行，感觉像假死了一样，能否给一个进度指示，或者直接显示执行过程。
2、能否增加本地已有历史数据显示
例如：“每日股票数据”下面显示“本地数据自2023-01-01至2023-04-31”，这个时间根据补齐的历史数据自动变化。

**Comment by lhw828** [comment]
刚才在日志中发现：
`2023-04-24 09:05:41,429 indicators_data_daily_job.prepare处理异常：list index out of range
2023-04-24 09:05:41,438 klinepattern_data_daily_job.prepare处理异常：list index out of range`
问题是不是出在这里？

**Comment by myhhub** [comment]
> 每日股票数据

ak.stock_zh_a_spot_em()，没有时间参数
每日股票数据,不可以补，错过了就没有。

**Comment by myhhub** [comment]
> 刚才在日志中发现：
> 
> 2023-04-24 09:05:42,096 数据库链接执行信息：mysql+pymysql://root:root@InStockDbService:3306/instockdb?charset=utf8mb4
> 
> 2023-04-24 09:05:42,177 stockfetch.fetch_stock_top_data处理异常：[Errno 32] Broken pipe
> 
> 2023-04-24 09:05:42,339 indicators_data_daily_job.prepare处理异常：list index out of range
> 
> 2023-04-24 09:05:42,341 klinepattern_data_daily_job.prepare处理异常：list index out of range
> 
> 2023-04-24 09:05:42,343 strategy_data_daily_job.prepare处理异常：{'name': 'cn_stock_strategy_enter', 'cn': '放量上涨', 'func': <function check_volume at 0x7f16d54374c0>,
> 
> 问题是不是出在这里？

这个时间段，抓不了数据。东财，或新浪都没数据

**Comment by lhw828** [comment]
> > 每日股票数据
> 
> ak.stock_zh_a_spot_em()，没有时间参数 每日股票数据,不可以补，错过了就没有。

了解。小白一枚，不懂就问。
我遇到的其实是历史数据补全，我想知道本地的历史数据，到底已经补充到哪一天了。粗浅的理解，回测的时候，应该是依赖历史数据的吧？

**Comment by lhw828** [comment]
> > 刚才在日志中发现：
> > 2023-04-24 09:05:42,096 数据库链接执行信息：mysql+pymysql://root:root@InStockDbService:3306/instockdb?charset=utf8mb4
> > 2023-04-24 09:05:42,177 stockfetch.fetch_stock_top_data处理异常：[Errno 32] Broken pipe
> > 2023-04-24 09:05:42,339 indicators_data_daily_job.prepare处理异常：list index out of range
> > 2023-04-24 09:05:42,341 klinepattern_data_daily_job.prepare处理异常：list index out of range
> > 2023-04-24 09:05:42,343 strategy_data_daily_job.prepare处理异常：{'name': 'cn_stock_strategy_enter', 'cn': '放量上涨', 'func': <function check_volume at 0x7f16d54374c0>,
> > 问题是不是出在这里？
> 
> 这个时间段，抓不了数据。东财，或新浪都没数据

那请问，目前历史数据能补到哪一天？

**Comment by lhw828** [comment]
> > 刚才在日志中发现：
> > 2023-04-24 09:05:42,096 数据库链接执行信息：mysql+pymysql://root:root@InStockDbService:3306/instockdb?charset=utf8mb4
> > 2023-04-24 09:05:42,177 stockfetch.fetch_stock_top_data处理异常：[Errno 32] Broken pipe
> > 2023-04-24 09:05:42,339 indicators_data_daily_job.prepare处理异常：list index out of range
> > 2023-04-24 09:05:42,341 klinepattern_data_daily_job.prepare处理异常：list index out of range
> > 2023-04-24 09:05:42,343 strategy_data_daily_job.prepare处理异常：{'name': 'cn_stock_strategy_enter', 'cn': '放量上涨', 'func': <function check_volume at 0x7f16d54374c0>,
> > 问题是不是出在这里？
> 
> 这个时间段，抓不了数据。东财，或新浪都没数据

https://tushare.pro/document/1  这个接口能不能试试？

**Comment by myhhub** [comment]
> 历史数据

历史数据可以补，可以补到9几年的

**Comment by myhhub** [comment]
> 

每日数据和历史数据栏目不同，每日数据跟多，具体看tablestructure.py

**Comment by myhhub** [comment]
关键你补历史数据有什么用？没有任何用途

**Comment by myhhub** [comment]
你看看代码就明白了，任何有用的数据我都已经纳入了。

**Comment by myhhub** [comment]
你要做的，根据系统的数据，算法，写自己的策略去赚钱

**Comment by lhw828** [comment]
好，谢谢。

继续提交错误信息：
python InStock/instock/job/backtest_data_daily_job.py           
ERROR:root:数据库链接执行信息：mysql+pymysql://root:root@InStockDbService:3306/instockdb?charset=utf8mb4
Traceback (most recent call last):
  File "/data/InStock/instock/job/backtest_data_daily_job.py", line 18, in <module>
    from instock.core.singleton import stock_hist_data
  File "/data/InStock/instock/core/singleton.py", line 7, in <module>
    import instock.core.stockfetch as stf
  File "/data/InStock/instock/core/stockfetch.py", line 12, in <module>
    import instock.lib.trade_time as trd
  File "/data/InStock/instock/lib/trade_time.py", line 5, in <module>
    from instock.core.singleton import stock_trade_date
ImportError: cannot import name 'stock_trade_date' from partially initialized module 'instock.core.singleton' (most likely due to a circular import) (/data/InStock/instock/core/singleton.py)

完全不懂代码哈，问了一下AI，他说是循环依赖，请确认

**Comment by myhhub** [comment]
历史数据的作用是，看k线，算指标及回测的，只要能够上网系统自己会去取。

**Comment by myhhub** [comment]
InStock\instock\cache\hist 里面就是最近3年股票的历史数据，因为它没用其他用所有没放在数据库。

**Comment by lhw828** [comment]
> 历史数据的作用是，看k线，算指标及回测的，只要能够上网系统自己会去取。

嗯，系统太强大了，我的思维还一直停留在通达信里面。

**Comment by CodeVeteran** [comment]
> InStock\instock\cache\hist 里面就是最近3年股票的历史数据，因为它没其他用所有没放在数据库。

我想把这些历史数据都 放到数据库里，需要改哪里？
