### ISSUE TITLE
执行backtest_data_daily_job.py遇到这个错误

### ISSUE THREAD

**Issue by lhw828** [myhhub/InStock#12]
一个错误信息：
python InStock/instock/job/backtest_data_daily_job.py
ERROR:root:数据库链接执行信息：mysql+pymysql://root:root@InStockDbService:3306/instockdb?charset=utf8mb4
Traceback (most recent call last):
File "/data/InStock/instock/job/backtest_data_daily_job.py", line 18, in
from instock.core.singleton import stock_hist_data
File "/data/InStock/instock/core/singleton.py", line 7, in
import instock.core.stockfetch as stf
File "/data/InStock/instock/core/stockfetch.py", line 12, in
import instock.lib.trade_time as trd
File "/data/InStock/instock/lib/trade_time.py", line 5, in
from instock.core.singleton import stock_trade_date
ImportError: cannot import name 'stock_trade_date' from partially initialized module 'instock.core.singleton' (most likely due to a circular import) (/data/InStock/instock/core/singleton.py)

**Comment by myhhub** [comment]
> 一个错误信息： python InStock/instock/job/backtest_data_daily_job.py ERROR:root:数据库链接执行信息：mysql+pymysql://root:root@InStockDbService:3306/instockdb?charset=utf8mb4 Traceback (most recent call last): File "/data/InStock/instock/job/backtest_data_daily_job.py", line 18, in from instock.core.singleton import stock_hist_data File "/data/InStock/instock/core/singleton.py", line 7, in import instock.core.stockfetch as stf File "/data/InStock/instock/core/stockfetch.py", line 12, in import instock.lib.trade_time as trd File "/data/InStock/instock/lib/trade_time.py", line 5, in from instock.core.singleton import stock_trade_date ImportError: cannot import name 'stock_trade_date' from partially initialized module 'instock.core.singleton' (most likely due to a circular import) (/data/InStock/instock/core/singleton.py)

插上你的网线

**Comment by myhhub** [comment]
> 一个错误信息： python InStock/instock/job/backtest_data_daily_job.py ERROR:root:数据库链接执行信息：mysql+pymysql://root:root@InStockDbService:3306/instockdb?charset=utf8mb4 Traceback (most recent call last): File "/data/InStock/instock/job/backtest_data_daily_job.py", line 18, in from instock.core.singleton import stock_hist_data File "/data/InStock/instock/core/singleton.py", line 7, in import instock.core.stockfetch as stf File "/data/InStock/instock/core/stockfetch.py", line 12, in import instock.lib.trade_time as trd File "/data/InStock/instock/lib/trade_time.py", line 5, in from instock.core.singleton import stock_trade_date ImportError: cannot import name 'stock_trade_date' from partially initialized module 'instock.core.singleton' (most likely due to a circular import) (/data/InStock/instock/core/singleton.py)

确实。已经修复
