### ISSUE TITLE
后期计划

### ISSUE THREAD

**Issue by bill816** [myhhub/InStock#14]
大佬，这个项目后期计划有什么呀，能否透露一下，有没有交流群什么的啊

**Comment by myhhub** [comment]
开发选股模块

**Comment by myhhub** [comment]
> 建议添加葵花向阳形态

请确认【葵花向阳】的公式。

REF:行轴正向移动N个周期，REF(C,1)表示昨天的收盘价
LLV:最低值，LLV(X,N)，求N周期内X最低值
BACKSET:向前赋值，BACKSET(X,N),若X非0,则将当前位置到N周期前的数值设为1。例如：BACKSET(CLOSE＞OPEN,2)若收阳则将该周期及前一周期数值设为1,否则为0
C:收盘价
ZF:=C/REF(C,1)*100-100;
SX:=C/LLV(C,7)>=1 4/100;

葵花向阳:=REF(SX,1) AND BACKSET(REF(ZF,3)>0.5 AND REF(ZF,2)>3 AND REF(ZF,1) <-2 AND ZF>3 AND C>REF(C,2),4);

**Comment by cybest2010** [comment]
您好，是的

**Comment by myhhub** [comment]
> 您好，是的
但这个公式是有问题的。
SX:=C/LLV(C,7)>=14/100;这永远成立，因为铁定C/LLV(C,7)>=1
