### ISSUE TITLE
自动交易模块的一个问题

### ISSUE THREAD

**Issue by gaojian110** [myhhub/InStock#16]
大佬，我看完交易模块代码，策略中的时钟间隔事件无法触发交易，那策略中的时钟间隔事件是用来做什么的？

**Comment by myhhub** [comment]
肯定会触发，它按时去完成交易，但要启动服务(trade_service.py)。

**Comment by gaojian110** [comment]
> 肯定会触发，它按时去完成交易，但要启动服务(trade_service.py)。
不好意思是我没描述清楚。是会触发策略里的clock函数，但clock函数里有个条件if event.data.clock_event == self.name，只有触发这个条件才能执行策略函数，但是时钟间隔事件的event.data.clock_event是为 [0.5, 1, 3, 5, 15, 30, 60]的其中一个，但是self.name='stratey1'，导致时钟间隔事件无法触发策略函数。
![T 8V9{Y54KN0MH75NHZ UKA](https://github.com/myhhub/InStock/assets/57975630/cd9763b2-b53b-4be9-b3ee-9d8aacfd92ed)
