### ISSUE TITLE
windows 添加定时任务执行龙虎榜数据插入失败

### ISSUE THREAD

**Issue by xycfree** [myhhub/InStock#17]
windows 添加定时任务执行龙虎榜数据插入失败， 提示联合主键冲突！
2023-05-17 17:00:41,554 database.insert_other_db_from_df处理异常：cn_stock_top表(pymysql.err.IntegrityError) (1062, "Duplicate entry '2023-05-17-000837' for key 'PRIMARY'")
[SQL: INSERT INTO cn_stock_top (date, code, name, ranking_times, sum_buy, sum_sell, net_amount, buy_seat, sell_seat) VALUES (%(date)s, %(code)s, %(name)s, %(ranking_times)s, %(sum_buy)s, %(sum_sell)s, %(net_amount)s, %(buy_seat)s, %(sell_seat)s)]
[parameters: [{'date': '2023-05-17', 'code': '002466', 'name': '天齐锂业', 'ranking_times': 1, 'sum_buy': 213352.66, 'sum_sell': 60243.1, 'net_amount': 153109.56, 'buy_seat': 5, 'sell_seat': 5}, {'date': '2023-05-17', 'code': '002865', 'name': '钧达股份', 'ranking_times': 1, 'sum_buy': 134457.2, 'sum_sell': 70349.35, 'net_amount': 64107.85, 'buy_seat': 5, 'sell_seat': 5}, {'date': '2023-05-17', 'code': '002756', 'name': '永兴材料', 'ranking_times': 1, 'sum_buy': 76713.02, 'sum_sell': 20841.48, 'net_amount': 55871.54, 'buy_seat': 3, 'sell_seat': 5}, {'date': '2023-05-17', 'code': '002240', 'name': '盛新锂能', 'ranking_times': 1, 'sum_buy': 58353.23, 'sum_sell': 11892.21, 'net_amount': 46461.01, 'buy_seat': 4, 'sell_seat': 5}, {'date': '2023-05-17', 'code': '002738', 'name': '中矿资源', 'ranking_times': 1, 'sum_buy': 71795.21, 'sum_sell': 36476.41, 'net_amount': 35318.8, 'buy_seat': 5, 'sell_seat': 5}, {'date': '2023-05-17', 'code': '002045', 'name': '国光电器', 'ranking_times': 3, 'sum_buy': 129581.85, 'sum_sell': 95597.68, 'net_amount': 33984.17, 'buy_seat': 10, 'sell_seat': 9}, {'date': '2023-05-17', 'code': '002459', 'name': '晶澳科技', 'ranking_times': 1, 'sum_buy': 78164.19, 'sum_sell': 47060.6, 'net_amount': 31103.59, 'buy_seat': 4, 'sell_seat': 3}, {'date': '2023-05-17', 'code': '000681', 'name': '视觉中国', 'ranking_times': 3, 'sum_buy': 257164.08, 'sum_sell': 229382.14, 'net_amount': 27781.95, 'buy_seat': 12, 'sell_seat': 15}  ... displaying 10 of 168 total bound parameter sets ...  {'date': '2023-05-17', 'code': '000617', 'name': '中油资本', 'ranking_times': 2, 'sum_buy': 119590.45, 'sum_sell': 144046.49, 'net_amount': -24456.04, 'buy_seat': 6, 'sell_seat': 8}, {'date': '2023-05-17', 'code': '600686', 'name': '金龙汽车', 'ranking_times': 1, 'sum_buy': 36903.99, 'sum_sell': 66260.86, 'net_amount': -29356.87, 'buy_seat': 6, 'sell_seat': 5}]]
(Background on this error at: https://sqlalche.me/e/20/gkpj)

**Comment by myhhub** [comment]
> windows 添加定时任务执行龙虎榜数据插入失败， 提示联合主键冲突！ 2023-05-17 17:00:41,554 database.insert_other_db_from_df处理异常：cn_stock_top表(pymysql.err.IntegrityError) (1062, "Duplicate entry '2023-05-17-000837' for key 'PRIMARY'") [SQL: INSERT INTO cn_stock_top (date, code, name, ranking_times, sum_buy, sum_sell, net_amount, buy_seat, sell_seat) VALUES (%(date)s, %(code)s, %(name)s, %(ranking_times)s, %(sum_buy)s, %(sum_sell)s, %(net_amount)s, %(buy_seat)s, %(sell_seat)s)] [parameters: [{'date': '2023-05-17', 'code': '002466', 'name': '天齐锂业', 'ranking_times': 1, 'sum_buy': 213352.66, 'sum_sell': 60243.1, 'net_amount': 153109.56, 'buy_seat': 5, 'sell_seat': 5}, {'date': '2023-05-17', 'code': '002865', 'name': '钧达股份', 'ranking_times': 1, 'sum_buy': 134457.2, 'sum_sell': 70349.35, 'net_amount': 64107.85, 'buy_seat': 5, 'sell_seat': 5}, {'date': '2023-05-17', 'code': '002756', 'name': '永兴材料', 'ranking_times': 1, 'sum_buy': 76713.02, 'sum_sell': 20841.48, 'net_amount': 55871.54, 'buy_seat': 3, 'sell_seat': 5}, {'date': '2023-05-17', 'code': '002240', 'name': '盛新锂能', 'ranking_times': 1, 'sum_buy': 58353.23, 'sum_sell': 11892.21, 'net_amount': 46461.01, 'buy_seat': 4, 'sell_seat': 5}, {'date': '2023-05-17', 'code': '002738', 'name': '中矿资源', 'ranking_times': 1, 'sum_buy': 71795.21, 'sum_sell': 36476.41, 'net_amount': 35318.8, 'buy_seat': 5, 'sell_seat': 5}, {'date': '2023-05-17', 'code': '002045', 'name': '国光电器', 'ranking_times': 3, 'sum_buy': 129581.85, 'sum_sell': 95597.68, 'net_amount': 33984.17, 'buy_seat': 10, 'sell_seat': 9}, {'date': '2023-05-17', 'code': '002459', 'name': '晶澳科技', 'ranking_times': 1, 'sum_buy': 78164.19, 'sum_sell': 47060.6, 'net_amount': 31103.59, 'buy_seat': 4, 'sell_seat': 3}, {'date': '2023-05-17', 'code': '000681', 'name': '视觉中国', 'ranking_times': 3, 'sum_buy': 257164.08, 'sum_sell': 229382.14, 'net_amount': 27781.95, 'buy_seat': 12, 'sell_seat': 15} ... displaying 10 of 168 total bound parameter sets ... {'date': '2023-05-17', 'code': '000617', 'name': '中油资本', 'ranking_times': 2, 'sum_buy': 119590.45, 'sum_sell': 144046.49, 'net_amount': -24456.04, 'buy_seat': 6, 'sell_seat': 8}, {'date': '2023-05-17', 'code': '600686', 'name': '金龙汽车', 'ranking_times': 1, 'sum_buy': 36903.99, 'sum_sell': 66260.86, 'net_amount': -29356.87, 'buy_seat': 6, 'sell_seat': 5}]] (Background on this error at: https://sqlalche.me/e/20/gkpj)

先确认是最新的，再发问题
