### ISSUE TITLE
社区&联系方式

### ISSUE THREAD

**Issue by IT-JAVA** [myhhub/InStock#18]
大佬，最近在研究量化，看到你的项目觉得做的非常强大，不知道是否有社群或者联系方式能添加下？有问题可以及时的请教下你

**Comment by myhhub** [comment]
> 大佬，最近在研究量化，看到你的项目觉得做的非常强大，不知道是否有社群或者联系方式能添加下？有问题可以及时的请教下你

请教不敢。有问题可以在这提，或发yh_ma@qq.com

**Comment by IT-JAVA** [comment]
好的，感谢
