### ISSUE TITLE
docker版无法选择日期

### ISSUE THREAD

**Issue by wbhinspector** [myhhub/InStock#19]
之前好好的，今天docker版更新后就这样了。
![image](https://github.com/myhhub/InStock/assets/39436441/267b69ff-7c34-46a1-9b89-699cc60a2743)

**Comment by myhhub** [comment]
> 之前好好的，今天docker版更新后就这样了。 ![image](https://user-images.githubusercontent.com/39436441/241184343-267b69ff-7c34-46a1-9b89-699cc60a2743.pn

> 之前好好的，今天docker版更新后就这样了。 ![image](https://user-images.githubusercontent.com/39436441/241184343-267b69ff-7c34-46a1-9b89-699cc60a2743.png)

清除浏览器缓存。js组件升级，还在使用缓存的js文件
