### ISSUE TITLE
加油啊，试了一天硬是没搭起来。。。

### ISSUE THREAD

**Issue by lidutech** [myhhub/InStock#2]
主要是Windows环境好久没用了，甚至connect mysql 都忘的七七八八，求个docker或者 Linux的branch

**Comment by myhhub** [comment]
以后会考虑的做docker镜像

**Comment by bill816** [comment]
花了一点时间搭起来了，在搭的过程中遇到的一个坑 import libs.stockfetch as stf 提示找不到 libs.stockfetch，发现是因为自己的python环境有libs库，pip uninstall libs就好了，目录名libs名字太通用了，大佬是否会改一下避免冲突。

**Comment by myhhub** [comment]
> 花了一点时间搭起来了，在搭的过程中遇到的一个坑 import libs.stockfetch as stf 提示找不到 libs.stockfetch，发现是因为自己的python环境有libs库，pip uninstall libs就好了，目录名libs名字太通用了，大佬是否会改一下避免冲突。

项目的目录结构不规范，正在规范化
