### ISSUE TITLE
无法安装ta-lib

### ISSUE THREAD

**Issue by IT-JAVA** [myhhub/InStock#20]
我在本地想通过pycharm启动该项目，可是ta-lib包试了很多办法都没办法安装成功，包括下面的方法都试了，通过conda倒是可以安装成功，可是使用conda里面的python interpreter又会有其他的包无法安装，还望大佬指点哈（windows笔记本）
------------------------------------------------------------------------------------------------------------------
第一种方法. pip 下安装
（1）https://www.ta-lib.org/下载并解压ta-lib-0.4.0-msvc.zip
（2）解压并将ta_lib放在C盘根目录
（3）https://visualstudio.microsoft.com/zh-hans/downloads/下载并安装Visual Studio Community，安装切记勾选Visual C++功能
（4）Build TA-Lib Library # 构建 TA-Lib 库
    ①在开始菜单中搜索并打开[Native Tools Command Prompt](根据操作系统选择32位或64位)
    ②输入 cd C:\ta-lib\c\make\cdr\win32\msvc
    ③构建库，输入 nmake
（5）安装完成。
第二种方法. Anaconda 下安装
（1）打开Anaconda Prompt终端。
（2）在终端输入命令行conda install -c conda-forge ta-lib 。
（3）此处确认是否继续安装？输入y 继续安装，直到完成
（4）安装完成。

**Comment by IT-JAVA** [comment]
可能是我操作不当，目前已经通过下面方式解决，谢谢
----
第一种方法. pip 下安装
（1）[https://www.ta-lib.org/下载并解压ta-lib-0.4.0-msvc.zip](https://www.ta-lib.org/%E4%B8%8B%E8%BD%BD%E5%B9%B6%E8%A7%A3%E5%8E%8Bta-lib-0.4.0-msvc.zip)
（2）解压并将ta_lib放在C盘根目录
（3）[https://visualstudio.microsoft.com/zh-hans/downloads/下载并安装Visual](https://visualstudio.microsoft.com/zh-hans/downloads/%E4%B8%8B%E8%BD%BD%E5%B9%B6%E5%AE%89%E8%A3%85Visual) Studio Community，安装切记勾选Visual C++功能
（4）Build TA-Lib Library # 构建 TA-Lib 库
①在开始菜单中搜索并打开[Native Tools Command Prompt](https://github.com/myhhub/InStock/issues/%E6%A0%B9%E6%8D%AE%E6%93%8D%E4%BD%9C%E7%B3%BB%E7%BB%9F%E9%80%89%E6%8B%A932%E4%BD%8D%E6%88%9664%E4%BD%8D)
②输入 cd C:\ta-lib\c\make\cdr\win32\msvc
③构建库，输入 nmake
（5）安装完成。

**Comment by xinmans** [comment]
ubuntu20.04下如何安装TA_lib呀
