### ISSUE TITLE
pandas only supports SQLAlchemy connectable 

### ISSUE THREAD

**Issue by royburns** [myhhub/InStock#21]
\InStock\instock\job\indicators_data_daily_job.py:99: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  data = pd.read_sql(sql=sql, con=mdb.conn_not_cursor())

data = pd.read_sql(sql=sql, con=mdb.conn_not_cursor())

替换为

data = pd.read_sql(sql=sql, con=mdb.engine())

**Comment by myhhub** [comment]
感谢宝贵建议！
pandas1.5.3版本的read_sql不支持sqlalchemy，2.0以后支持了。
