### ISSUE TITLE
docker镜像好像不是最新的

### ISSUE THREAD

**Issue by IT-JAVA** [myhhub/InStock#22]
这个新加的综合选股模块是不是镜像没有打？目前docker拉的好像没有这块内容啊？
--
![e0ac8b5160eab69641e5e1b76fba79a](https://github.com/myhhub/InStock/assets/17808835/6d0850dd-06c1-403e-968f-f4a2656ec358)

**Comment by myhhub** [comment]
该版本购买了商业软件，无法进行开源操作
