### ISSUE TITLE
如何增加ETF指数相关场内基金

### ISSUE THREAD

**Issue by bill816** [myhhub/InStock#4]
代码拉下来跑了一下，发现只有股票数据，找不到比如沪深300ETF相关场内基金，这块能否加进去，或者能否告诉下如何加入自己想要关注的其他标的，感谢~

**Comment by myhhub** [comment]
通过下面方法获取：
https://www.akshare.xyz/data/fund/fund_public.html#id6
1.获取ETF列表
ak.fund_etf_category_sina(symbol=""ETF基金")
2.获取历史行情数据
ak.fund_etf_hist_sina(symbol="sz169103")

**Comment by myhhub** [comment]
> 代码拉下来跑了一下，发现只有股票数据，找不到比如沪深300ETF相关场内基金，这块能否加进去，或者能否告诉下如何加入自己想要关注的其他标的，感谢~


纳入了ETF数据

**Comment by myhhub** [comment]
> 代码拉下来跑了一下，发现只有股票数据，找不到比如沪深300ETF相关场内基金，这块能否加进去，或者能否告诉下如何加入自己想要关注的其他标的，感谢~


纳入了ETF数据
