### ISSUE TITLE
是否可以提供一个docker镜像

### ISSUE THREAD

**Issue by yirenyishi** [myhhub/InStock#7]
是否可以提供一个docker镜像，这样可以省去很多环境相关的问题

**Comment by myhhub** [comment]
列在项目计划中

**Comment by lhw828** [comment]
已入坑，遇到的问题太多。等docker~

**Comment by johnsonhongyi** [comment]
期待docker,自动后台同步数据,刚刚安装上,数据一目了然,方便快捷,可否添加周K等周期选择形态数据筛选,查看形态以便择时,
