### ISSUE TITLE
Could not build wheels for TA_Lib, which is required to install pyproject.toml-based projects

### ISSUE THREAD

**Issue by lhw828** [myhhub/InStock#8]
Building wheels for collected packages: TA_Lib
  Building wheel for TA_Lib (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Building wheel for TA_Lib (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [183 lines of output]
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build\lib.win-amd64-cpython-311
      creating build\lib.win-amd64-cpython-311\talib
      copying talib\abstract.py -> build\lib.win-amd64-cpython-311\talib
      copying talib\deprecated.py -> build\lib.win-amd64-cpython-311\talib
      copying talib\stream.py -> build\lib.win-amd64-cpython-311\talib
      copying talib\test_abstract.py -> build\lib.win-amd64-cpython-311\talib
      copying talib\test_data.py -> build\lib.win-amd64-cpython-311\talib
      copying talib\test_func.py -> build\lib.win-amd64-cpython-311\talib
      copying talib\test_pandas.py -> build\lib.win-amd64-cpython-311\talib
      copying talib\test_polars.py -> build\lib.win-amd64-cpython-311\talib
      copying talib\test_stream.py -> build\lib.win-amd64-cpython-311\talib
      copying talib\__init__.py -> build\lib.win-amd64-cpython-311\talib
      running build_ext
      building 'talib._ta_lib' extension
      creating build\temp.win-amd64-cpython-311
      creating build\temp.win-amd64-cpython-311\Release
      creating build\temp.win-amd64-cpython-311\Release\talib
      "d:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\x86_amd64\cl.exe" /c /nologo /O2 /W3 /GL /DNDEBUG /MD -Ic:\ta-lib\c\include -IC:\Users\Administrator\AppData\Local\Temp\pip-build-env-0os7be3w\normal\Lib\site-packages\numpy\core\include -IC:\Users\Administrator\AppData\Local\Programs\Python\Python311\include -IC:\Users\Administrator\AppData\Local\Programs\Python\Python311\Include "-Id:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE" "-Id:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\ATLMFC\INCLUDE" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.22000.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.22000.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.22000.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.22000.0\winrt" /Tctalib/_ta_lib.c /Fobuild\temp.win-amd64-cpython-311\Release\talib/_ta_lib.obj
      _ta_lib.c
      c:\users\administrator\appdata\local\temp\pip-build-env-0os7be3w\normal\lib\site-packages\numpy\core\include\numpy\npy_1_7_deprecated_api.h(14) : Warning Msg: Using deprecated NumPy API, disable it with #define NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION
      talib/_ta_lib.c(7052): warning C4146: 一元负运算符应用于无符号类型，结果仍为无符号类型
      talib/_ta_lib.c(7057): warning C4146: 一元负运算符应用于无符号类型，结果仍为无符号类型
      talib/_ta_lib.c(7247): warning C4146: 一元负运算符应用于无符号类型，结果仍为无符号类型
      talib/_ta_lib.c(7429): warning C4146: 一元负运算符应用于无符号类型，结果仍为无符号类型
      talib/_ta_lib.c(7611): warning C4146: 一元负运算符应用于无符号类型，结果仍为无符号类型
      talib/_ta_lib.c(7616): warning C4146: 一元负运算符应用于无符号类型，结果仍为无符号类型
      talib/_ta_lib.c(7774): warning C4146: 一元负运算符应用于无符号类型，结果仍为无符号类型
      talib/_ta_lib.c(7952): warning C4146: 一元负运算符应用于无符号类型，结果仍为无符号类型
      talib/_ta_lib.c(8300): warning C4146: 一元负运算符应用于无符号类型，结果仍为无符号类型
      talib/_ta_lib.c(8676): warning C4146: 一元负运算符应用于无符号类型，结果仍为无符号类型
      talib/_ta_lib.c(8869): warning C4146: 一元负运算符应用于无符号类型，结果仍为无符号类型
      talib/_ta_lib.c(9226): warning C4146: 一元负运算符应用于无符号类型，结果仍为无符号类型
      talib/_ta_lib.c(20762): warning C4146: 一元负运算符应用于无符号类型，结果仍为无符号类型
      talib/_ta_lib.c(20915): warning C4146: 一元负运算符应用于无符号类型，结果仍为无符号类型
      talib/_ta_lib.c(21241): warning C4146: 一元负运算符应用于无符号类型，结果仍为无符号类型
      talib/_ta_lib.c(21550): warning C4146: 一元负运算符应用于无符号类型，结果仍为无符号类型
      talib/_ta_lib.c(21710): warning C4146: 一元负运算符应用于无符号类型，结果仍为无符号类型
      talib/_ta_lib.c(22578): warning C4146: 一元负运算符应用于无符号类型，结果仍为无符号类型
      talib/_ta_lib.c(22720): warning C4146: 一元负运算符应用于无符号类型，结果仍为无符号类型
      talib/_ta_lib.c(22862): warning C4146: 一元负运算符应用于无符号类型，结果仍为无符号类型
      talib/_ta_lib.c(23004): warning C4146: 一元负运算符应用于无符号类型，结果仍为无符号类型
      talib/_ta_lib.c(23146): warning C4146: 一元负运算符应用于无符号类型，结果仍为无符号类型
      talib/_ta_lib.c(23473): warning C4146: 一元负运算符应用于无符号类型，结果仍为无符号类型
      talib/_ta_lib.c(23642): warning C4146: 一元负运算符应用于无符号类型，结果仍为无符号类型
      talib/_ta_lib.c(23647): warning C4146: 一元负运算符应用于无符号类型，结果仍为无符号类型
      talib/_ta_lib.c(23652): warning C4146: 一元负运算符应用于无符号类型，结果仍为无符号类型
      talib/_ta_lib.c(23874): warning C4146: 一元负运算符应用于无符号类型，结果仍为无符号类型
      talib/_ta_lib.c(23884): warning C4146: 一元负运算符应用于无符号类型，结果仍为无符号类型
      talib/_ta_lib.c(23894): warning C4146: 一元负运算符应用于无符号类型，结果仍为无符号类型
      talib/_ta_lib.c(24066): warning C4146: 一元负运算符应用于无符号类型，结果仍为无符号类型
      talib/_ta_lib.c(24439): warning C4146: 一元负运算符应用于无符号类型，结果仍为无符号类型
      talib/_ta_lib.c(24444): warning C4146: 一元负运算符应用于无符号类型，结果仍为无符号类型
      talib/_ta_lib.c(24601): warning C4146: 一元负运算符应用于无符号类型，结果仍为无符号类型
      talib/_ta_lib.c(24743): warning C4146: 一元负运算符应用于无符号类型，结果仍为无符号类型
      talib/_ta_lib.c(25076): warning C4146: 一元负运算符应用于无符号类型，结果仍为无符号类型
      talib/_ta_lib.c(25244): warning C4146: 一元负运算符应用于无符号类型，结果仍为无符号类型
      talib/_ta_lib.c(25397): warning C4146: 一元负运算符应用于无符号类型，结果仍为无符号类型
      talib/_ta_lib.c(25549): warning C4146: 一元负运算符应用于无符号类型，结果仍为无符号类型
      talib/_ta_lib.c(25691): warning C4146: 一元负运算符应用于无符号类型，结果仍为无符号类型
      talib/_ta_lib.c(25846): warning C4146: 一元负运算符应用于无符号类型，结果仍为无符号类型
      talib/_ta_lib.c(26003): warning C4146: 一元负运算符应用于无符号类型，结果仍为无符号类型
      talib/_ta_lib.c(26205): warning C4146: 一元负运算符应用于无符号类型，结果仍为无符号类型
      talib/_ta_lib.c(26376): warning C4146: 一元负运算符应用于无符号类型，结果仍为无符号类型
      talib/_ta_lib.c(26528): warning C4146: 一元负运算符应用于无符号类型，结果仍为无符号类型
      talib/_ta_lib.c(26837): warning C4146: 一元负运算符应用于无符号类型，结果仍为无符号类型
      talib/_ta_lib.c(27164): warning C4146: 一元负运算符应用于无符号类型，结果仍为无符号类型
      talib/_ta_lib.c(27335): warning C4146: 一元负运算符应用于无符号类型，结果仍为无符号类型
      talib/_ta_lib.c(27509): warning C4146: 一元负运算符应用于无符号类型，结果仍为无符号类型
      talib/_ta_lib.c(27514): warning C4146: 一元负运算符应用于无符号类型，结果仍为无符号类型
      talib/_ta_lib.c(27661): warning C4146: 一元负运算符应用于无符号类型，结果仍为无符号类型
      talib/_ta_lib.c(27803): warning C4146: 一元负运算符应用于无符号类型，结果仍为无符号类型
      talib/_ta_lib.c(27945): warning C4146: 一元负运算符应用于无符号类型，结果仍为无符号类型
      talib/_ta_lib.c(28087): warning C4146: 一元负运算符应用于无符号类型，结果仍为无符号类型
      talib/_ta_lib.c(28229): warning C4146: 一元负运算符应用于无符号类型，结果仍为无符号类型
      talib/_ta_lib.c(28999): warning C4146: 一元负运算符应用于无符号类型，结果仍为无符号类型
      talib/_ta_lib.c(29239): warning C4146: 一元负运算符应用于无符号类型，结果仍为无符号类型
      talib/_ta_lib.c(29452): warning C4146: 一元负运算符应用于无符号类型，结果仍为无符号类型
      talib/_ta_lib.c(29457): warning C4146: 一元负运算符应用于无符号类型，结果仍为无符号类型
      talib/_ta_lib.c(29467): warning C4146: 一元负运算符应用于无符号类型，结果仍为无符号类型
      talib/_ta_lib.c(29691): warning C4146: 一元负运算符应用于无符号类型，结果仍为无符号类型
      talib/_ta_lib.c(29696): warning C4146: 一元负运算符应用于无符号类型，结果仍为无符号类型
      talib/_ta_lib.c(29909): warning C4146: 一元负运算符应用于无符号类型，结果仍为无符号类型
      talib/_ta_lib.c(29914): warning C4146: 一元负运算符应用于无符号类型，结果仍为无符号类型
      talib/_ta_lib.c(29919): warning C4146: 一元负运算符应用于无符号类型，结果仍为无符号类型
      talib/_ta_lib.c(30226): warning C4146: 一元负运算符应用于无符号类型，结果仍为无符号类型
      talib/_ta_lib.c(30379): warning C4146: 一元负运算符应用于无符号类型，结果仍为无符号类型
      talib/_ta_lib.c(30700): warning C4146: 一元负运算符应用于无符号类型，结果仍为无符号类型
      talib/_ta_lib.c(31006): warning C4146: 一元负运算符应用于无符号类型，结果仍为无符号类型
      talib/_ta_lib.c(31148): warning C4146: 一元负运算符应用于无符号类型，结果仍为无符号类型
      talib/_ta_lib.c(31290): warning C4146: 一元负运算符应用于无符号类型，结果仍为无符号类型
      talib/_ta_lib.c(31640): warning C4146: 一元负运算符应用于无符号类型，结果仍为无符号类型
      talib/_ta_lib.c(31645): warning C4146: 一元负运算符应用于无符号类型，结果仍为无符号类型
      talib/_ta_lib.c(31650): warning C4146: 一元负运算符应用于无符号类型，结果仍为无符号类型
      talib/_ta_lib.c(31821): warning C4146: 一元负运算符应用于无符号类型，结果仍为无符号类型
      talib/_ta_lib.c(32154): warning C4146: 一元负运算符应用于无符号类型，结果仍为无符号类型
      talib/_ta_lib.c(32314): warning C4146: 一元负运算符应用于无符号类型，结果仍为无符号类型
      talib/_ta_lib.c(40940): warning C4146: 一元负运算符应用于无符号类型，结果仍为无符号类型
      talib/_ta_lib.c(40945): warning C4146: 一元负运算符应用于无符号类型，结果仍为无符号类型
      talib/_ta_lib.c(41134): warning C4146: 一元负运算符应用于无符号类型，结果仍为无符号类型
      talib/_ta_lib.c(41312): warning C4146: 一元负运算符应用于无符号类型，结果仍为无符号类型
      talib/_ta_lib.c(41490): warning C4146: 一元负运算符应用于无符号类型，结果仍为无符号类型
      talib/_ta_lib.c(41495): warning C4146: 一元负运算符应用于无符号类型，结果仍为无符号类型
      talib/_ta_lib.c(41643): warning C4146: 一元负运算符应用于无符号类型，结果仍为无符号类型
      talib/_ta_lib.c(41816): warning C4146: 一元负运算符应用于无符号类型，结果仍为无符号类型
      talib/_ta_lib.c(42137): warning C4146: 一元负运算符应用于无符号类型，结果仍为无符号类型
      talib/_ta_lib.c(42508): warning C4146: 一元负运算符应用于无符号类型，结果仍为无符号类型
      talib/_ta_lib.c(42693): warning C4146: 一元负运算符应用于无符号类型，结果仍为无符号类型
      talib/_ta_lib.c(43042): warning C4146: 一元负运算符应用于无符号类型，结果仍为无符号类型
      talib/_ta_lib.c(54503): warning C4146: 一元负运算符应用于无符号类型，结果仍为无符号类型
      talib/_ta_lib.c(54646): warning C4146: 一元负运算符应用于无符号类型，结果仍为无符号类型
      talib/_ta_lib.c(54945): warning C4146: 一元负运算符应用于无符号类型，结果仍为无符号类型
      talib/_ta_lib.c(55237): warning C4146: 一元负运算符应用于无符号类型，结果仍为无符号类型
      talib/_ta_lib.c(55393): warning C4146: 一元负运算符应用于无符号类型，结果仍为无符号类型
      talib/_ta_lib.c(56175): warning C4146: 一元负运算符应用于无符号类型，结果仍为无符号类型
      talib/_ta_lib.c(56307): warning C4146: 一元负运算符应用于无符号类型，结果仍为无符号类型
      talib/_ta_lib.c(56439): warning C4146: 一元负运算符应用于无符号类型，结果仍为无符号类型
      talib/_ta_lib.c(56571): warning C4146: 一元负运算符应用于无符号类型，结果仍为无符号类型
      talib/_ta_lib.c(56703): warning C4146: 一元负运算符应用于无符号类型，结果仍为无符号类型
      talib/_ta_lib.c(57000): warning C4146: 一元负运算符应用于无符号类型，结果仍为无符号类型
      talib/_ta_lib.c(57159): warning C4146: 一元负运算符应用于无符号类型，结果仍为无符号类型
      talib/_ta_lib.c(57164): warning C4146: 一元负运算符应用于无符号类型，结果仍为无符号类型
      talib/_ta_lib.c(57169): warning C4146: 一元负运算符应用于无符号类型，结果仍为无符号类型
      talib/_ta_lib.c(57383): warning C4146: 一元负运算符应用于无符号类型，结果仍为无符号类型
      talib/_ta_lib.c(57393): warning C4146: 一元负运算符应用于无符号类型，结果仍为无符号类型
      talib/_ta_lib.c(57403): warning C4146: 一元负运算符应用于无符号类型，结果仍为无符号类型
      talib/_ta_lib.c(57567): warning C4146: 一元负运算符应用于无符号类型，结果仍为无符号类型
      talib/_ta_lib.c(57924): warning C4146: 一元负运算符应用于无符号类型，结果仍为无符号类型
      talib/_ta_lib.c(57929): warning C4146: 一元负运算符应用于无符号类型，结果仍为无符号类型
      talib/_ta_lib.c(58079): warning C4146: 一元负运算符应用于无符号类型，结果仍为无符号类型
      talib/_ta_lib.c(58211): warning C4146: 一元负运算符应用于无符号类型，结果仍为无符号类型
      talib/_ta_lib.c(58514): warning C4146: 一元负运算符应用于无符号类型，结果仍为无符号类型
      talib/_ta_lib.c(58681): warning C4146: 一元负运算符应用于无符号类型，结果仍为无符号类型
      talib/_ta_lib.c(58824): warning C4146: 一元负运算符应用于无符号类型，结果仍为无符号类型
      talib/_ta_lib.c(58969): warning C4146: 一元负运算符应用于无符号类型，结果仍为无符号类型
      talib/_ta_lib.c(59101): warning C4146: 一元负运算符应用于无符号类型，结果仍为无符号类型
      talib/_ta_lib.c(59233): warning C4146: 一元负运算符应用于无符号类型，结果仍为无符号类型
      talib/_ta_lib.c(59382): warning C4146: 一元负运算符应用于无符号类型，结果仍为无符号类型
      talib/_ta_lib.c(59553): warning C4146: 一元负运算符应用于无符号类型，结果仍为无符号类型
      talib/_ta_lib.c(59720): warning C4146: 一元负运算符应用于无符号类型，结果仍为无符号类型
      talib/_ta_lib.c(59865): warning C4146: 一元负运算符应用于无符号类型，结果仍为无符号类型
      talib/_ta_lib.c(60157): warning C4146: 一元负运算符应用于无符号类型，结果仍为无符号类型
      talib/_ta_lib.c(60473): warning C4146: 一元负运算符应用于无符号类型，结果仍为无符号类型
      talib/_ta_lib.c(60640): warning C4146: 一元负运算符应用于无符号类型，结果仍为无符号类型
      talib/_ta_lib.c(60807): warning C4146: 一元负运算符应用于无符号类型，结果仍为无符号类型
      talib/_ta_lib.c(60812): warning C4146: 一元负运算符应用于无符号类型，结果仍为无符号类型
      talib/_ta_lib.c(60949): warning C4146: 一元负运算符应用于无符号类型，结果仍为无符号类型
      talib/_ta_lib.c(61081): warning C4146: 一元负运算符应用于无符号类型，结果仍为无符号类型
      talib/_ta_lib.c(61213): warning C4146: 一元负运算符应用于无符号类型，结果仍为无符号类型
      talib/_ta_lib.c(61345): warning C4146: 一元负运算符应用于无符号类型，结果仍为无符号类型
      talib/_ta_lib.c(61477): warning C4146: 一元负运算符应用于无符号类型，结果仍为无符号类型
      talib/_ta_lib.c(62203): warning C4146: 一元负运算符应用于无符号类型，结果仍为无符号类型
      talib/_ta_lib.c(62423): warning C4146: 一元负运算符应用于无符号类型，结果仍为无符号类型
      talib/_ta_lib.c(62626): warning C4146: 一元负运算符应用于无符号类型，结果仍为无符号类型
      talib/_ta_lib.c(62631): warning C4146: 一元负运算符应用于无符号类型，结果仍为无符号类型
      talib/_ta_lib.c(62641): warning C4146: 一元负运算符应用于无符号类型，结果仍为无符号类型
      talib/_ta_lib.c(62863): warning C4146: 一元负运算符应用于无符号类型，结果仍为无符号类型
      talib/_ta_lib.c(62868): warning C4146: 一元负运算符应用于无符号类型，结果仍为无符号类型
      talib/_ta_lib.c(63079): warning C4146: 一元负运算符应用于无符号类型，结果仍为无符号类型
      talib/_ta_lib.c(63084): warning C4146: 一元负运算符应用于无符号类型，结果仍为无符号类型
      talib/_ta_lib.c(63089): warning C4146: 一元负运算符应用于无符号类型，结果仍为无符号类型
      talib/_ta_lib.c(63381): warning C4146: 一元负运算符应用于无符号类型，结果仍为无符号类型
      talib/_ta_lib.c(63524): warning C4146: 一元负运算符应用于无符号类型，结果仍为无符号类型
      talib/_ta_lib.c(63815): warning C4146: 一元负运算符应用于无符号类型，结果仍为无符号类型
      talib/_ta_lib.c(64107): warning C4146: 一元负运算符应用于无符号类型，结果仍为无符号类型
      talib/_ta_lib.c(64239): warning C4146: 一元负运算符应用于无符号类型，结果仍为无符号类型
      talib/_ta_lib.c(64371): warning C4146: 一元负运算符应用于无符号类型，结果仍为无符号类型
      talib/_ta_lib.c(64707): warning C4146: 一元负运算符应用于无符号类型，结果仍为无符号类型
      talib/_ta_lib.c(64712): warning C4146: 一元负运算符应用于无符号类型，结果仍为无符号类型
      talib/_ta_lib.c(64717): warning C4146: 一元负运算符应用于无符号类型，结果仍为无符号类型
      talib/_ta_lib.c(64884): warning C4146: 一元负运算符应用于无符号类型，结果仍为无符号类型
      talib/_ta_lib.c(65203): warning C4146: 一元负运算符应用于无符号类型，结果仍为无符号类型
      talib/_ta_lib.c(65359): warning C4146: 一元负运算符应用于无符号类型，结果仍为无符号类型
      "d:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\x86_amd64\link.exe" /nologo /INCREMENTAL:NO /LTCG /DLL /MANIFEST:EMBED,ID=2 /MANIFESTUAC:NO /LIBPATH:c:\ta-lib\c\lib /LIBPATH:C:\Users\Administrator\AppData\Local\Programs\Python\Python311\libs /LIBPATH:C:\Users\Administrator\AppData\Local\Programs\Python\Python311 /LIBPATH:C:\Users\Administrator\AppData\Local\Programs\Python\Python311\PCbuild\amd64 "/LIBPATH:d:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\LIB\amd64" "/LIBPATH:d:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\ATLMFC\LIB\amd64" "/LIBPATH:C:\Program Files (x86)\Windows Kits\10\lib\10.0.22000.0\ucrt\x64" "/LIBPATH:C:\Program Files (x86)\Windows Kits\10\lib\10.0.22000.0\um\x64" ta_libc_cdr.lib /EXPORT:PyInit__ta_lib build\temp.win-amd64-cpython-311\Release\talib/_ta_lib.obj /OUT:build\lib.win-amd64-cpython-311\talib\_ta_lib.cp311-win_amd64.pyd /IMPLIB:build\temp.win-amd64-cpython-311\Release\talib\_ta_lib.cp311-win_amd64.lib
      _ta_lib.obj : warning LNK4197: 多次指定导出“PyInit__ta_lib”；使用第一个规范
        正在创建库 build\temp.win-amd64-cpython-311\Release\talib\_ta_lib.cp311-win_amd64.lib 和对象 build\temp.win-amd64-cpython-311\Release\talib\_ta_lib.cp311-win_amd64.exp
      正在生成代码
      已完成代码的生成
      LINK : fatal error LNK1158: 无法运行“rc.exe”
      error: command 'd:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\BIN\\x86_amd64\\link.exe' failed with exit code 1158
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for TA_Lib
Failed to build TA_Lib
ERROR: Could not build wheels for TA_Lib, which is required to install pyproject.toml-based projects

已按照https://github.com/myhhub/InStock#4%E5%AE%89%E8%A3%85-talib 编译了talib，现在卡在这里，过不去

**Comment by myhhub** [comment]
Microsoft Visual Studio版本太低，越新越好

**Comment by lhw828** [comment]
Visual Studio 2022
